### ISSUE TITLE
How do you stay consistent?

### ISSUE THREAD

**Issue by JunaidQadirB** [shanselman/ama#54]
Hey @shanselman, 
I really love this idea of AMA!.
OK, You work for one of the tech giants still you are persistent and consistent with your online life like managing to do over five hundred podcast episodes. and Azure friday and doing stuff like modding games and playing with 3d printing and what not!

How do you do that?

I used to blog but I couldn't continue, 
Then I tried a podcast which i did once in two weeks but only could do 7 episodes before I stopped.
Then I tried to do a podcast I called it [#100DayPodcastChallenge](https://www.youtube.com/playlist?list=PLqIOJQ6wfsNQaEfK2RLl6IH6oecM-d8Ii) which was a daily podcast I did to fix my speaking skills. I ended up doing only ten episodes and couldn't continue that as well.

Regards,

**Comment by shanselman** [comment]
Why did you stop?

**Comment by JunaidQadirB** [comment]
I've no idea to be honest. 
But to record one episode that was shorter than 5 minutes, It took  me 3-4 hours. That struggle I guess was the problem. I take a lot of time to decide my topic. and I used to decide the topic on the day I was about to record.

**Comment by Im5tu** [comment]
Preparation & planning is key if you are going to anything for an extended period of time. Something that a lot of people I know do is prepare content in advance - so this might mean that you record a couple of podcasts in a day to be released over a few days. Gives you that extra breathing room when you're ahead with your content. Same goes for writing blog posts & social media posts to some extent.

**Comment by wmeints** [comment]
My blogging goes on and off. I sometimes don't find the inspiration to write something. I guess because my work doesn't contain a lot that I want to write about at that time. Other times I write 3 posts a week easily. 

I think you need to be aware of topics you can speak/write/vlog about. Most of the times it's the small things that other people haven't noticed.

I have a huge respect for people like you Scott. The amount of content you push out is amazing.

**Comment by Nick-Lucas** [comment]
What @Im5tu says is true. I used to produce tutorial content on Youtube, and I would block together the brainstorming and writing, then production and uploading of 5-10 episodes at a time, then set them to release once a week. It's way more efficient to just sit down and do a load of research on many different topics; more enjoyable too, because you get to really explore the subjects.

It's also good, because if you're trying to build a brand, being able to focus on marketing and responding to comments as the episodes release is really important. Having distractions like producing "next week's episode" really gets in the way of enjoying the whole process.

**Comment by shanselman** [comment]
Awesome answers here! Thank you all!

**Comment by bsimser** [comment]
I was an active blogger years ago (along with a SharePoint MVP for 10 years). Then I just ran out of steam. Trying to come up with topics wasn't the issue, it was focusing on getting the content done. A long time down while we took care of our special needs daughter meant no travelling, no blogging, etc. Times have changed now and it's a struggle to try to get back but you can, you just need to keep at it and find that passion again. Find the spark and keep it lit.

**Comment by MrAlex6204** [comment]
I think the best way to do something fast is practicing a lot, the first time it take a long time but when you got more than one hundred of practice you will be fast enough like a ninja. 

Practice a bunch of things daily you can do all these in a short time.

If you're a fast coder but when you try to do videos in youtube without a knowledge in production video , you will spend a lot of time in one video for you'r vlog.

The same thing happen if you're a fast coder but when you don't have experience in physics and you trying to code a game without this knowledge.

The same concept applies for a buch of thing like trying to learn a new language(I mean Chinese,Mexican,Russian).
