### ISSUE TITLE
What are your thoughts on the google diversity memo issue? was firing the correct decision?

### ISSUE THREAD

**Issue by DarylSmith** [shanselman/ama#78]

**Comment by shanselman** [comment]
It's not something that's easily handled, in either a tweet sized statement or a 10 page memo, it seems. I also don't know enough of the HR background of this guy. Should someone be fired for "having an opinion?" Well, free speech gives you the right to have an opinion but it doesn't prevent people from not liking your opinion. If your coworker is a Nazi, we should fire them, right? Pedophile? Sure, these are agreed upon standards in society and these are extreme views and not the same as what this guy wrote. But, when someone has unpopular or uncomfortable opinions that are on an edge and if those opinions start to affect the workplace or make the workplace hostile for a class of people, then that gets more dodgy. Yes, men and women are different. Yes, gender is fluid and a spectrum. People are different. It's OK to see color. These things make life interesting and personal interactions interesting. However, making declarations - veiled or not - that a class of people aren't intrinsically good at an intellectual pursuit, be it math, programming, or knitting, is going to be a problem. I don't know what they should have done, I'm not a CEO, thank goodness. I would probably hold a town hall or company meeting. Conversations need to be had, in person, not on twitter. It's complex.

All that said, I'm going to keep doing what I'm doing. I will continue to unapologetically lend my privilege to raise the voices of women and PoC so that they may enjoy long careers in tech like I have.

**Comment by RobBlob** [comment]
Maybe he should apply for a job at Uber, would probably fit better with that corporate culture.
