### ISSUE TITLE
Tips & tricks: Microsoft MVP

### ISSUE THREAD

**Issue by gabrielrobert** [shanselman/ama#82]
What are the best tips you could advise someone wanting to become Microsoft MVP?

**Comment by DanAtkinson** [comment]
This is going to sound like a snide comment but I genuinely mean it with respect because this question is somewhat surprising to to me.

In my opinion, this sounds like a very self-serving question. Surely just doing a good job (optional: and getting paid for it) should be reward enough. Or do you feel that you need your worth to be validated by an organisation?

Being an MVP ***shouldn't*** be seen as a goal but rather a recognition of one's achievements; sort of like the icing on top of the cake.

**Comment by ghuntley** [comment]
Do amazing stuff; teach and mentor. Then self-nominate (this is okay) or hope someone notices the cool things you are doing in the community and nominates you.

> Or do you feel that you need your worth to be validated by an organisation?

Very important and true. MVP is a thing that is useful to re-affirm credibility you have already earned by doing really cool things.

**Comment by matthewblott** [comment]
@DanAtkinson excellent point. The Ruby community had something called 'Ruby Heroes' which has now been retired precisely because the initial spirit seemed to get lost and was motivating people for the wrong reasons. More on it [here](http://olivierlacan.com/posts/ruby-heroes-farewell/).

**Comment by IEvangelist** [comment]
I was recently awarded **Microsoft MVP**, and [I was interviewed](https://twitter.com/LisaAnderson312/status/895357997836374016) about the process. I encourage you to have a look. Being an MVP just means that Microsoft recognizes all your community efforts - which is amazing. However, if you're truly passionate about giving back to the developer community that should be enough.

One tip that I would encourage is becoming a social developer, jump down to ["The Social Developer"](https://medium.com/@davidpine7/the-story-of-a-lonely-developer-fear-not-you-are-not-alone-8d3f42b7c89e) section of this post.

**Comment by gabrielrobert** [comment]
Thank you, guys! 👍
