### ISSUE TITLE
Is MS working on .Net targeting WebAssembly so that we can get delivered from the insanity of JavaScript?

### ISSUE THREAD

**Issue by Zintjr** [shanselman/ama#85]
It would be really nice to have a "SilverLight like" web development experience where we have a Xaml UI  framework that replaces the DOM and code can be written in C#/F# instead of JavaScript.  Is Microsoft working to make that happen with .Net and WebAssembly (or any other technology)? Thanks!

**Comment by shanselman** [comment]
Yes https://github.com/SteveSanderson/Blazor

**Comment by RobBlob** [comment]
That's very good news. Next go for delivering us from CSS

**Comment by Terricide** [comment]
They could go this direction.
http://www.cshtml5.com/

or

http://www.zebkit.com/ and render directly to the canvas

**Comment by viniciussalvati** [comment]
I saw today that mono is attempting the same thing. http://www.mono-project.com/news/2017/08/09/hello-webassembly/

There is also Fable (Google for f# fable). It's  not Web assembly, but it's something. And since they're doing this, they could make f# compile to Web assembly (even if without the .NET Framework)
